language: go
script: make docker-integration-test
services:
  - docker
matrix:
  include:
    - go: 1.12
      env:
        - DOCKER_COMPOSE_VERSION=1.23.2
        - GO111MODULE=on
    - go: 1.11
      env:
        - DOCKER_COMPOSE_VERSION=1.23.2
        - GO111MODULE=on
