version: '2'
services:
  fileserver:
    image: python:3
    command:
      - python3
      - -m
      - http.server
    ports:
      - 8000:8000
  rate-one:
    build:
      context: .
    command:
      - -rpm=100
      - -etcd-addresses=http://etcd:2379
      - http://fileserver:8000
    depends_on:
      - fileserver
      - etcd
    ports:
      - 4040:4040
  rate-two:
    build:
      context: .
    command:
      - -rpm=100
      - -port=4041
      - -etcd-addresses=http://etcd:2379
      - http://fileserver:8000
    depends_on:
      - fileserver
      - etcd
    ports:
      - 4041:4041
  etcd:
    image: quay.io/coreos/etcd:v3.3.0
    command:
      - /usr/local/bin/etcd
      - -name=etcd1
      - -advertise-client-urls=http://0.0.0.0:2379
      - -initial-advertise-peer-urls=http://0.0.0.0:2380
      - -listen-client-urls=http://0.0.0.0:2379
      - -listen-peer-urls=http://0.0.0.0:2380
      - -initial-cluster=etcd1=http://0.0.0.0:2380
    ports:
      - 2379:2379
      - 2380:2380
